//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PasswordManager.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string Form_ContextMenu_AddContainer {
            get {
                return ResourceManager.GetString("Form_ContextMenu_AddContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string Form_ContextMenu_AddPassword {
            get {
                return ResourceManager.GetString("Form_ContextMenu_AddPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        internal static string Form_ContextMenu_DeleteContainer {
            get {
                return ResourceManager.GetString("Form_ContextMenu_DeleteContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename folder.
        /// </summary>
        internal static string Form_ContextMenu_RenameContainer {
            get {
                return ResourceManager.GetString("Form_ContextMenu_RenameContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string Form_Listview_Caption {
            get {
                return ResourceManager.GetString("Form_Listview_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Form_Listview_ID {
            get {
                return ResourceManager.GetString("Form_Listview_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Form_Listview_Password {
            get {
                return ResourceManager.GetString("Form_Listview_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Form_MenuItem_About {
            get {
                return ResourceManager.GetString("Form_MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Form_MenuItem_Language {
            get {
                return ResourceManager.GetString("Form_MenuItem_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Form_MenuItem_Language_English {
            get {
                return ResourceManager.GetString("Form_MenuItem_Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string Form_MenuItem_Language_Japanese {
            get {
                return ResourceManager.GetString("Form_MenuItem_Language_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string Form_MenuItem_Option {
            get {
                return ResourceManager.GetString("Form_MenuItem_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed symbols.
        /// </summary>
        internal static string Form_NewPassword_AllowedSymbols {
            get {
                return ResourceManager.GetString("Form_NewPassword_AllowedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Form_NewPassword_Cancel {
            get {
                return ResourceManager.GetString("Form_NewPassword_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string Form_NewPassword_Caption {
            get {
                return ResourceManager.GetString("Form_NewPassword_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Form_NewPassword_ErrorDialogCaption {
            get {
                return ResourceManager.GetString("Form_NewPassword_ErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Chars is too large.
        /// </summary>
        internal static string Form_NewPassword_ErrorMaxTooLarge {
            get {
                return ResourceManager.GetString("Form_NewPassword_ErrorMaxTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Chars cannot exceed Max Chars.
        /// </summary>
        internal static string Form_NewPassword_ErrorMinLTMax {
            get {
                return ResourceManager.GetString("Form_NewPassword_ErrorMinLTMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Chars is too small.
        /// </summary>
        internal static string Form_NewPassword_ErrorMinTooSmall {
            get {
                return ResourceManager.GetString("Form_NewPassword_ErrorMinTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate(&amp;G).
        /// </summary>
        internal static string Form_NewPassword_Generate {
            get {
                return ResourceManager.GetString("Form_NewPassword_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Form_NewPassword_ID {
            get {
                return ResourceManager.GetString("Form_NewPassword_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max chars.
        /// </summary>
        internal static string Form_NewPassword_MaxChars {
            get {
                return ResourceManager.GetString("Form_NewPassword_MaxChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string Form_NewPassword_Memo {
            get {
                return ResourceManager.GetString("Form_NewPassword_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min chars.
        /// </summary>
        internal static string Form_NewPassword_MinChars {
            get {
                return ResourceManager.GetString("Form_NewPassword_MinChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Form_NewPassword_OK {
            get {
                return ResourceManager.GetString("Form_NewPassword_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Form_NewPassword_PasswdNormal {
            get {
                return ResourceManager.GetString("Form_NewPassword_PasswdNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong.
        /// </summary>
        internal static string Form_NewPassword_PasswdSecure {
            get {
                return ResourceManager.GetString("Form_NewPassword_PasswdSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak.
        /// </summary>
        internal static string Form_NewPassword_PasswdWeak {
            get {
                return ResourceManager.GetString("Form_NewPassword_PasswdWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Form_NewPassword_Password {
            get {
                return ResourceManager.GetString("Form_NewPassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize password.
        /// </summary>
        internal static string Form_NewPassword_Randomize {
            get {
                return ResourceManager.GetString("Form_NewPassword_Randomize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password strength test.
        /// </summary>
        internal static string Form_NewPassword_StrengthTest {
            get {
                return ResourceManager.GetString("Form_NewPassword_StrengthTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use lower case.
        /// </summary>
        internal static string Form_NewPassword_UseLowercase {
            get {
                return ResourceManager.GetString("Form_NewPassword_UseLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use numeric.
        /// </summary>
        internal static string Form_NewPassword_UseNumeric {
            get {
                return ResourceManager.GetString("Form_NewPassword_UseNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use symbol.
        /// </summary>
        internal static string Form_NewPassword_UseSymbolic {
            get {
                return ResourceManager.GetString("Form_NewPassword_UseSymbolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use upper case.
        /// </summary>
        internal static string Form_NewPassword_UseUppercase {
            get {
                return ResourceManager.GetString("Form_NewPassword_UseUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Password.
        /// </summary>
        internal static string Form_NewPassword_WndTitle {
            get {
                return ResourceManager.GetString("Form_NewPassword_WndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string Form_Tooltip_OpenFile {
            get {
                return ResourceManager.GetString("Form_Tooltip_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        internal static string Form_Tooltip_SaveFile {
            get {
                return ResourceManager.GetString("Form_Tooltip_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All characters are different each other.
        /// </summary>
        internal static string General_NewPassword_Strength_AllDifferent {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_AllDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower case only.
        /// </summary>
        internal static string General_NewPassword_Strength_L {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of lower case / number.
        /// </summary>
        internal static string General_NewPassword_Strength_LN {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_LN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of lower case / number / symbol.
        /// </summary>
        internal static string General_NewPassword_Strength_LNS {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_LNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of lower case / symbol.
        /// </summary>
        internal static string General_NewPassword_Strength_LS {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of lower case / upper case.
        /// </summary>
        internal static string General_NewPassword_Strength_LU {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_LU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of lower case / upper case / number.
        /// </summary>
        internal static string General_NewPassword_Strength_LUN {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_LUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of lower case / upper case / number / symbol.
        /// </summary>
        internal static string General_NewPassword_Strength_LUNS {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_LUNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of lower case / upper case / symbol.
        /// </summary>
        internal static string General_NewPassword_Strength_LUS {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_LUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number only.
        /// </summary>
        internal static string General_NewPassword_Strength_N {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of number / symbol.
        /// </summary>
        internal static string General_NewPassword_Strength_NS {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol only.
        /// </summary>
        internal static string General_NewPassword_Strength_S {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same characters are in a row.
        /// </summary>
        internal static string General_NewPassword_Strength_SameCharInARow {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_SameCharInARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} chars of the same type are in a row.
        /// </summary>
        internal static string General_NewPassword_Strength_SameClassInARow {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_SameClassInARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of consecutive {0} chars are different.
        /// </summary>
        internal static string General_NewPassword_Strength_SameClassNotInARow {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_SameClassNotInARow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Bad].
        /// </summary>
        internal static string General_NewPassword_Strength_TypeBad {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_TypeBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Good].
        /// </summary>
        internal static string General_NewPassword_Strength_TypeGood {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_TypeGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Class&gt;.
        /// </summary>
        internal static string General_NewPassword_Strength_TypePassClass {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_TypePassClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SCORE&gt;.
        /// </summary>
        internal static string General_NewPassword_Strength_TypeResult {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_TypeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper case only.
        /// </summary>
        internal static string General_NewPassword_Strength_U {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of upper case / number.
        /// </summary>
        internal static string General_NewPassword_Strength_UN {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of upper case / number / symbol.
        /// </summary>
        internal static string General_NewPassword_Strength_UNS {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_UNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combination of upper case / symbol.
        /// </summary>
        internal static string General_NewPassword_Strength_US {
            get {
                return ResourceManager.GetString("General_NewPassword_Strength_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Status_Ready {
            get {
                return ResourceManager.GetString("Status_Ready", resourceCulture);
            }
        }
    }
}
